version: '3'

services: 
  app:
    build: .
    container_name: nodejs_app_product
    restart: on-failure
    ports:
      - "3030:3030"
    volumes: 
      - .:/app/src
      - nodemodules:/src/node_modules

volumes: 
  nodemodules: {}